#!/bin/sh
# Publish built application to Github Pages

set -e

# delete gh-pages branches if the exist
git branch -D gh-pages || true
git push origin --delete gh-pages || true

# build on master
git checkout master
npm run build

# push to newly createg gh-pages branch
git checkout -b gh-pages
sed -i 's|/dist|#/dist|' .gitignore
git add dist/
git commit -m 'Build'
git subtree push --prefix dist/ origin gh-pages

# switch back to master
sed -i 's|#/dist|/dist|' .gitignore
git checkout master
