#!/bin/bash
# Run the application inside a docker container.
# To add new npm packages use docker-exec(1), e.g.:
# docker exec -t ${CONTAINER_NAME} npm install my-new-pkg --save

CONTAINER_NAME="$(pwd | tr / '\n' | tail -1 | sed 's|[- ]|_|g')"
DOCKER_COMMAND="docker"
DOCKER_IMAGE="juankman94/myfinances"
WD="$PWD"
SCRIPT="run serve"

# check current environment
case "$(uname)" in
	CYGWIN*)
		DOCKER_COMMAND="winpty docker"
		WD="$(cygpath -w $PWD)"
		;;
esac

if [ -n "$1" ]; then
	if [ "$1" = "install" ]; then
		SCRIPT="$1"
	else
		SCRIPT="run $1"
	fi
fi

$DOCKER_COMMAND run \
	--name ${CONTAINER_NAME} \
	--rm \
	-it \
	-w /app \
	-v "$WD:/app" \
	-p 8000:8000 \
	${DOCKER_IMAGE} \
	npm ${SCRIPT}
